### ISSUE TITLE
odoo 16 için kendisi çalışma yapıyor

### ISSUE THREAD

**Issue by tate11** [odoo-turkey/l10n-turkey#4]
https://github.com/odoo-dev/odoo/commit/946170c9d7411cd4c3fa6184956fb56528b2769e

**Comment by yibudak** [comment]
Merhaba, belirtilen commit mevcut değil. Odoo'nun içerisinde default olarak gelen l10n_tr modülü v8'den beri güncellenmiyor.

**Comment by tate11** [comment]
Evet o commit silinmiş alttaki linki kontrol edeblilrsiz . v16 yetiştirememişler sanırım v17 gelir.

https://github.com/odoo-dev/odoo/commit/f69ae774e707df2eb6e011175e6cb01d3a9c9679#commitcomment-85010486

[tate11](https://github.com/tate11) commented on [f69ae77](https://github.com/odoo-dev/odoo/commit/f69ae774e707df2eb6e011175e6cb01d3a9c9679) [29 days ago](https://github.com/odoo-dev/odoo/commit/f69ae774e707df2eb6e011175e6cb01d3a9c9679#commitcomment-85010301)

Will this Turkish CoA development be merged with v16

@poma-odoo
Author
[poma-odoo](https://github.com/poma-odoo) commented on [f69ae77](https://github.com/odoo-dev/odoo/commit/f69ae774e707df2eb6e011175e6cb01d3a9c9679) [29 days ago](https://github.com/odoo-dev/odoo/commit/f69ae774e707df2eb6e011175e6cb01d3a9c9679#commitcomment-85010486)

**Nope, V16 has been frozen.**
